# site_name: My Docs
# theme:
#   name: material
#Site
site_name: Data Analytics Lifecycle Processes & Standardization
site_url: https://gk0209.github.io/DatabricksLearning/
site_author: Girish Kumar
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project
# Repository
repo_name: Databricks Learning
repo_url: https://github.com/GK0209/DatabricksLearning
edit_uri: ""

# Custom Colour Pallete
extra_css:
    - stylesheets/extra.css

# Configuration
theme:
    name: material
    # Default values, taken from mkdocs_theme.yml
    language: en
    features:
        - content.code.annotate
        - content.tabs.link
        - navigation.expand
        - navigation.indexes
        - navigation.instant
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        # - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
    palette:
        - scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono
    #favicon: assets/favicon.png
    #logo: assets/favicon.png

extra:
    generator: false

plugins:
    - search
    - autorefs
    - mkdocstrings

markdown_extensions:
    - attr_list
    - meta
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true

nav:
    - Fundamentals: fundamnetal/fundamental.md
    - Advance: advance/advance.md
    - Lab Exercise: lab/exercise.md     
    